### ISSUE TITLE
Release a Ubuntu package please

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [Cretezy/i3-back#1]
:)

**Comment by Cretezy** [comment]
Will look into it, I haven't packaged anything in `.deb` in a while.

In the meantime, the Cargo install is just 2 commands and should work everywhere:

```
# from https://rustup.rs/
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

cargo install
```

Or the pre-built binary works too.

**Comment by Cretezy** [comment]
[v0.1.3](https://github.com/Cretezy/i3-back/releases) includes a Debian/Ubuntu `deb` package. Please test and let me know if it works correctly!
